apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: employee-service-signed
spec:
  images:
    - glob: "docker.io/rahulkishorparida/employee-service**"

  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: "https://github.com/rahulkishorparida/employee-service/.github/workflows/ci-cd.yml@refs/heads/main"
      ctlog:
        url: https://rekor.sigstore.dev