apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: istio-proxy-trusted
spec:
  images:
    - glob: "registry.istio.io/release/proxyv2:1.30.4@**"

  authorities:
    - static:
        action: pass