apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: employee-service-istio
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: employee-service
  podMetricsEndpoints:
    - targetPort: 15020
      path: /stats/prometheus
      interval: 15s